### ISSUE TITLE
 缺个东西吧，不能运行

### ISSUE THREAD

**Issue by vihuela** [kymjs/CodeCafe#3]
Caused by: java.lang.NullPointerException
                                                       at java.io.File.fixSlashes(File.java:185)
                                                       at java.io.File.<init>(File.java:134)
                                                       at com.kymjs.nuwa.Nuwa.loadPatch(Nuwa.java:47)
                                                       at com.kymjs.nuwa.Nuwa.init(Nuwa.java:38)
                                                       at top.codecafe.AppContext.attachBaseContext(AppContext.java:17)

**Comment by nianzhen** [comment]
Caused by: java.lang.NullPointerException
    at java.io.File.fixSlashes(File.java:195)
    at java.io.File.<init>(File.java:144)
    at com.kymjs.nuwa.Nuwa.loadPatch(Nuwa.java:47)
    at com.kymjs.nuwa.Nuwa.init(Nuwa.java:38)
    2016年6月8日16:03:19 导入没有文件

**Comment by kymjs** [comment]
不需要nuwa模块，删掉就可以了
