### ISSUE TITLE
Crashed when app starting on Galaxy S5 

### ISSUE THREAD

**Issue by mickyliu945** [kymjs/CodeCafe#6]
FATAL EXCEPTION: main
                                                              Process: top.codecafe, PID: 24809
                                                              java.lang.RuntimeException: Unable to instantiate application top.codecafe.AppContext: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:625)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4980)
                                                                  at android.app.ActivityThread.access$1600(ActivityThread.java:172)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:145)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5832)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                  at java.io.File.fixSlashes(File.java:185)
                                                                  at java.io.File.<init>(File.java:134)
                                                                  at com.kymjs.nuwa.Nuwa.loadPatch(Nuwa.java:47)
                                                                  at com.kymjs.nuwa.Nuwa.init(Nuwa.java:38)
                                                                  at top.codecafe.AppContext.attachBaseContext(AppContext.java:17)
                                                                  at android.app.Application.attach(Application.java:205)
                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
                                                                  at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                                                                  at android.app.LoadedApk.makeApplication(LoadedApk.java:620)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4980) 
                                                                  at android.app.ActivityThread.access$1600(ActivityThread.java:172) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:145) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5832) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by mickyliu945** [comment]
I fixed as followed:
//        if (!new File(dexPath).exists()) {
//            Log.e(TAG, dexPath + " is null");
//            return;
//        }

**Comment by shesio** [comment]
good

**Comment by chengfangpeng** [comment]
```
 if (TextUtils.isEmpty(dexPath) || !new File(dexPath).exists()) {
            Log.e(TAG, dexPath + " is null");
            return;
        }
```
